[build]
publish = "./apps/web/out/"
command = "npm run build"
environment = { NODE_VERSION = "20.10.0" }

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "https://www.sitecoremaster.com/*"
to = "https://dylanyoung.dev/"
status = 301
force = true

[[redirects]]
from = "https://sitecoremaster.com/*"
to = "https://dylanyoung.dev/"
status = 301
force = true

[[redirects]]
from = "/sugcon-eu-2024/*"
to = "/speaking/sugcon-europe-2024/:splat"
status = 301
force = true