name: parseSanityResult
archived: false
description: 'Take the result and parse into a friendly object'
friendlyId: parseSanityResult_102zztia11
type: DECISION
status: PUBLISHED
icon: ''
additionalFields:
  decisionOutputReference: 'SanityArticleResult'
  decisionReturnType: 'Map'
defaultTemplate: false
tags:
  - Source Control
customTemplate: true